Issue #4: Add setup github simulator and test scripts
* First run the setup a docker image with the current script

./setup-github-simulator.sh

* Any time you change the validator, you can re-run the setup
* This will also create an SSH file to interact with the server
* The setup output will show the command-line needed to run
the test script with

* Test the github config repo, running test.sh in the directory
  of the repo, specifying GITHUB_SIMULATOR_SSH_PATH

./test.sh

**** Example Setting up

$ ./setup-github-simulator.sh

Thu Apr 25 23:15:41 PDT 2019

* Setting up a Github Server simulator

==========--------- Building the new docker image -----------==========

* docker-compose build

Building intuit-spring-cloud-config-validator
Step 1/6 : FROM marcellodesales/github-enterprise-prereceive-hook-base
 ---> ef045e4c014b
Step 2/6 : MAINTAINER Marcello_deSales@intuit.com
 ---> Using cache
 ---> 4192a1953b48
Step 3/6 : RUN apk add --no-cache py-pip
 ---> Using cache
 ---> e565e39b59fe
Step 4/6 : COPY requirements.txt requirements.txt
 ---> Using cache
 ---> c35424b372ab
Step 5/6 : RUN pip2 install -r requirements.txt
 ---> Using cache
 ---> b736627be61c
Step 6/6 : COPY ./validate_config_files.py /home/git/test.git/hooks/pre-receive
 ---> e4c6d6e5ab27
Successfully built e4c6d6e5ab27
Successfully tagged intuit/intuit-spring-cloud-config-validator:latest

==========--------- Start the data container -----------==========

* docker run --name data intuit/intuit-spring-cloud-config-validator /bin/true

data
data

==========--------- Start a new Github Server simulator -----------==========

* docker run --name gitrepo -e GITHUB_PULL_REQUEST_HEAD=00000000 -e GITHUB_PULL_REQUEST_BASE=f394274 -d -p 52311:22 --volumes-from data -e GIT_DIR=/home/git/test.git intuit/intuit-spring-cloud-config-validator

gitrepo
gitrepo
29ca5e2af47bfaa40ac7fdef35857bbf5c707915aaf23abb0fe91b9a479ca689

==========--------- Copying credentials from Github server Container -----------==========

* docker cp data:/home/git/.ssh/id_rsa /Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/id_rsa_from_github_simulator_server

Thu Apr 25 23:15:47 PDT 2019

* Finished setting up the server...
* Now you can run tests with test.sh copying the command below:

GITHUB_SIMULATOR_SSH_PATH=/Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/id_rsa_from_github_simulator_server ./test.sh

***** Example Testing App

$ GITHUB_SIMULATOR_SSH_PATH=/Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/id_rsa_from_github_simulator_server BRANCH=marcello ./test.sh

Thu Apr 25 23:34:16 PDT 2019

* Executing the validations in local Github repo

==========--------- Github Config Repo -----------==========

* Current Dir: /Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/config-msaas-test-svc-01-config

total 88
drwxr-xr-x  17 mdesales  CORP\Domain Users   544 Apr 25 23:17 .
drwxr-xr-x  15 mdesales  CORP\Domain Users   480 Apr 25 23:20 ..
drwxr-xr-x  14 mdesales  CORP\Domain Users   448 Apr 25 23:34 .git
-rw-r--r--   1 mdesales  CORP\Domain Users    33 Apr 25 15:16 README.md
-rw-r--r--   1 mdesales  CORP\Domain Users   243 Apr 25 15:16 application.yml
-rw-r--r--   1 mdesales  CORP\Domain Users   499 Apr 25 19:08 config_msaas_test_01-dev.yml
-rw-r--r--   1 mdesales  CORP\Domain Users   494 Apr 25 15:16 config_msaas_test_01-e2e.yml
-rw-r--r--   1 mdesales  CORP\Domain Users   494 Apr 25 15:16 config_msaas_test_01-prd.yml
-rw-r--r--   1 mdesales  CORP\Domain Users   494 Apr 25 15:16 config_msaas_test_01-prf.yml
-rw-r--r--   1 mdesales  CORP\Domain Users   494 Apr 25 15:16 config_msaas_test_01-qal.yml
-rw-r--r--   1 mdesales  CORP\Domain Users   358 Apr 25 15:16 config_msaas_test_01.yml
-rw-------   1 mdesales  CORP\Domain Users  3243 Dec  6  2017 id_rsa_from_github_simulator_server
drwxr-xr-x   5 mdesales  CORP\Domain Users   160 Apr 25 19:08 idps
-rw-r--r--   1 mdesales  CORP\Domain Users     6 Apr 25 22:55 marcello.ssh
drwxr-xr-x   3 mdesales  CORP\Domain Users    96 Apr 25 23:18 super-dir
-rwxr-xr-x   1 mdesales  CORP\Domain Users  2304 Apr 25 22:18 test.sh
drwxr-xr-x   6 mdesales  CORP\Domain Users   192 Apr 25 15:20 venv

==========--------- Setting Test Remote Origin -----------==========

* Adding the git origin to current directory with server at 172.28.110.65

==========--------- Testing Remote Origin -----------==========

* Conectivity with the repo...
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 52311 -i /Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/id_rsa_from_github_simulator_server" git remote show test

Warning: Permanently added '[172.28.110.65]:52311' (ECDSA) to the list of known hosts.
* remote test
  Fetch URL: git@172.28.110.65:test.git
  Push  URL: git@172.28.110.65:test.git
  HEAD branch: master
  Remote branch:
    master new (next fetch will store in remotes/test)
  Local ref configured for 'git push':
    master pushes to master (up to date)

==========--------- Testing Remote Origin -----------==========

* Executing 'git push' to test github simulator
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 52311 -i /Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/id_rsa_from_github_simulator_server" git push -u test master
Warning: Permanently added '[172.28.110.65]:52311' (ECDSA) to the list of known hosts.
Branch 'master' set up to track remote branch 'master' from 'test'.
Everything up-to-date

* Testing additional branch marcello
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 52311 -i /Users/mdesales/dev/github/public/intuit/intuit-spring-cloud-config-validator/id_rsa_from_github_simulator_server" git push test marcello -f
Warning: Permanently added '[172.28.110.65]:52311' (ECDSA) to the list of known hosts.
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 8 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (16/16), 1.78 KiB | 608.00 KiB/s, done.
Total 16 (delta 5), reused 0 (delta 0)
remote: #####################################################
remote: ### Intuit Spring Cloud Config Validator 1.1.1 ####
remote: #####################################################
remote: Validating new branch...
remote: Processing commit=e869f048e6186f27910cdfcd40feaf285fe0c1d1 ref=refs/heads/marcello
remote: => Validating SHA e869f048e6186f27910cdfcd40feaf285fe0c1d1
remote: Filtering Spring Cloud Config Server's files:  ['**/*.json', '**/*.yaml', '**/*.yml', '**/*.properties']
remote: (v) File config_msaas_test_01-e2e.yml is valid!
remote: (x) File config_msaas_test_01-dev.yml is invalid: [13:4: syntax error: mapping values are not allowed here]
remote: (v) File config_msaas_test_01-prd.yml is valid!
remote: (x) File idps/idps.yaml is invalid: [2:33: syntax error: mapping values are not allowed here]
remote: (v) File config_msaas_test_01.yml is valid!
remote: (v) File config_msaas_test_01-prf.yml is valid!
remote: (v) File config_msaas_test_01-qal.yml is valid!
remote: (v) File application.yml is valid!
To 172.28.110.65:test.git
 ! [remote rejected] marcello -> marcello (pre-receive hook declined)
error: failed to push some refs to 'git@172.28.110.65:test.git'