CFG-174: Fixing Multiple docs per Yaml file delimited by dashes
Loading a yaml file, with multiple documents, was returning the following
error:

=> Validating directory /Users/akulkarni5/git/sp-boot-sample-config/
Traceback (most recent call last):
  File "./validate-config-files.py", line 203, in <module>
    validationIndex = validateConfigs(currentDirPath)
  File "./validate-config-files.py", line 154, in validateConfigs
    fileValidatesIndex[configFileName] = isYamlFileValid(configFileName)
  File "./validate-config-files.py", line 137, in isYamlFileValid
    yaml.load(open(filePath), Loader = yaml.Loader)
  File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 43, in get_single_node
    event.start_mark)
yaml.composer.ComposerError: expected a single document in the stream
  in "/Users/akulkarni5/git/sp-boot-sample-config/application.yml", line 27, column 1
but found another document
  in "/Users/akulkarni5/git/sp-boot-sample-config/application.yml", line 30, column 1

According to https://bitbucket.org/ruamel/yaml/issues/34/ruamelyaml-doesnt-preserve-dashes,
the fix is simple and requires using the other method call.

With the fix, the error is now validated as follows:

$ ./validate-config-files.py ~/dev/github/intuit/java-service-kit/sp-boot-sample-config
=> Validating directory /Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config
✔ File /Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config/sp_boot_sample-prd.yml is valid!
✔ File /Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config/sp_boot_sample-prf.yml is valid!
✔ File /Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config/sp_boot_sample-qal.yml is valid!
✘ File /Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config/application.yml is NOT valid: mapping values are not allowed here
  in "/Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config/application.yml", line 29, column 5
✔ File /Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config/sp_boot_sample-e2e.yml is valid!
✔ File /Users/mdesales/dev/github/intuit/java-service-kit/sp-boot-sample-config/sp_boot_sample-dev.yml is valid!

*	modified:   validate-config-files.py
- Fixing the error handling, capturing all