CFG-174: Externalizing all methods as classes: 3 modes execution: 0.1.1
Upgrading to version 0.1.1 with support to test cases.

* Using as a script: As usual, the validation verifies the current dir.

~/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator
on  feature/make-validator-oop! ⌚ 22:57:06
$ ./validate_config_files.py
=> Validating directory
/home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator
✘ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/.matrix-android.json is NOT valid: No JSON object could be decoded
✔ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu.yaml is valid!
✔ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-android.yml is valid!
✘ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-ios_8.0.yml is NOT valid: expected '<document start>', but found '<scalar>'
  in
"/home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-ios_8.0.yml", line 1, column 5
✔ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-ios.yml is valid!
✔ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-android_6.0.yml is valid!
✘ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/application.properties
is NOT valid: local variable 'wspacere' referenced before assignment
✔ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-2.7.yml is valid!
✔ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/.matrix-ios.json is valid!
✔ File /home/mdesales/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-android_N.yml is valid!

* Using as a Pre-receive hook: AS usual, it verifies the current commit changes.

~/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator/ttu-config
on  master ⌚ 22:58:20
$ GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o
StrictHostKeyChecking=no -p 52311 -i ../id_rsa" git push -u test master
Warning: Permanently added '[192.168.154.132]:52311' (ECDSA) to the list
of known hosts.
Counting objects: 214, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (100/100), done.
Writing objects: 100% (214/214), 21.50 KiB | 0 bytes/s, done.
Total 214 (delta 127), reused 184 (delta 109)
remote: ##################################################
remote: ###### Spring Cloud Config Validator 0.1.1 #######
remote: ##################################################
remote: Processing base=0000000000000000000000000000000000000000
commit=6ff408ac89564c994925c46847d775fff940caa3 ref=refs/heads/master
remote: => Validating SHA 6ff408ac89564c994925c46847d775fff940caa3
remote: ✔ File .matrix-ios.json is valid!
remote: ✘ File .matrix-android.json is NOT valid: Extra data: line 2
column 11 - line 29 column 1 (char 11 - 394)
To git@192.168.154.132:test.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@192.168.154.132:test.git'

* Using as dependency for Test cases: the dependency will verify the cases

~/dev/github/intuit/servicesplatform-tools/spring-cloud-config-validator
on  feature/make-validator-oop! ⌚ 22:57:08
$ python -m tests.test_basic
Executing test cases...
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK